default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character.
  - id: check-docstring-first
  - id: check-added-large-files
    args: ['--maxkb=512']

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.5.0
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
  hooks:
  - id: autopep8
    args:
    - --in-place
    - --aggressive
    - --aggressive
    - --ignore=E114,E115,E116,E133,E203,E401,E501,E701,W292

- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: migrations
    args:
        - --ignore=W503,W504,E123,E127,E203,E225,E241,E261,E265,E303,E501,F403,F405,C901
